#!/bin/sh

OPTIND=1
while getopts ":d:" opt; do
    case $opt in
        d) MAC="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

bt-device -i $MAC | rg 'Connected: 1' > /dev/null
CONNECTED=$?
if [[ $CONNECTED -eq 0 ]]; then
  echo "" # full text
  echo "Connected" # short text
else
  exit 0
fi
