#!/bin/bash

if [ "$instance" ]; then
  PCTLARGS="-p $instance"
  playerctl $PCTLARGS status > /dev/null
  if [[ $? -gt 0 ]]; then
    echo "" && exit
  fi
else
  PCTLARGS="-a"
fi

STATUS=$(playerctl -p $instance status)
if [[ "$STATUS" = "Playing" ]]; then
  # Check if has artist
  if [[ "$(playerctl $PCTLARGS)" ]]; then # Only print title
    playerctl $PCTLARGS metadata title
  else
    playerctl $PCTLARGS metadata --format "{{ artist }} - {{ title }}"
  fi
else
  echo "" && exit
fi
