#!/bin/bash

if [ "$instance" ]; then
  PCTLARGS="-p $instance"
  playerctl $PCTLARGS status > /dev/null
  if [[ $? -gt 0 ]]; then
    echo "" && exit
  fi
else
  PCTLARGS="-a"
fi

case $BLOCK_BUTTON in
  1) playerctl $PCTLARGS next ;;
  2) playerctl $PCTLARGS play-pause ;;
  3) playerctl $PCTLARGS prev ;;
  4) playerctl $PCTLARGS position 5+ ;;
  5) playerctl $PCTLARGS position 5- ;;
esac

STATUS=$(playerctl -p $instance status)
if [[ "$STATUS" = "Playing" ]]; then
  # Check if has artist
  if [[ "$(playerctl $PCTLARGS)" ]]; then # Only print title
    playerctl $PCTLARGS metadata title
  else
    playerctl $PCTLARGS metadata --format "{{ artist }} - {{ title }}"
  fi
else
  echo "" && exit
fi
