colors:
  # Default colors
  primary:
    background: '0xfafafa'
    foreground: '0x494b53'

  # Normal colors
  normal:
    # NOTE: Use '0x131613' for the `black` color if you'd like to see
    # black text on the background.
    black: '0xfafafa'
    red: '0xe45649'
    green: '0x50a14f'
    yellow: '0x986801'
    blue: '0x4078f2'
    magenta: '0xa626a4'
    cyan: '0x0184bc'
    white: '0x494b53'

  # Bright colors
  bright:
    black: '0xa0a1a7'
    red: '0xe45649'
    green: '0x50a14f'
    yellow: '0x986801'
    blue: '0x4078f2'
    magenta: '0xa626a4'
    cyan: '0x0184bc'
    white: '0x494b53'
