# Vars
  HISTFILE=~/.zsh_history
  SAVEHIST=1000 
  setopt inc_append_history # To save every command before it is executed 
  setopt share_history # setopt inc_append_history

# Aliases
  alias v="nvim -p"

  # This is currently causing problems (fails when you run it anywhere that isn't a git project's root directory)
  # alias vs="v `git status --porcelain | sed -ne 's/^ M //p'`"

# Settings
  export VISUAL=vim

source ~/dotfiles/zsh/plugins/fixls.zsh

# For vim mappings: 
stty -ixon

source ~/dotfiles/zsh/plugins/oh-my-zsh/lib/history.zsh
source ~/dotfiles/zsh/plugins/oh-my-zsh/lib/key-bindings.zsh
source ~/dotfiles/zsh/plugins/oh-my-zsh/lib/completion.zsh
source ~/dotfiles/zsh/plugins/oh-my-zsh/plugins/dnf/dnf.plugin.zsh
source ~/dotfiles/zsh/plugins/oh-my-zsh/plugins/tmux/tmux.plugin.zsh
source ~/dotfiles/zsh/plugins/oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh
source ~/dotfiles/zsh/plugins/vi-mode.plugin.zsh
source ~/dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/dotfiles/zsh/keybindings.sh

# Fix for arrow-key searching
# start typing + [Up-Arrow] - fuzzy find history forward
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
# start typing + [Down-Arrow] - fuzzy find history backward
if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi

source ~/dotfiles/zsh/prompt.sh

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle :compinstall filename '/home/rik/.zshrc'

autoload -Uz compinit
compinit
