# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

export VISUAL=nvim
export EDITOR=nvim

export PROMPT_DIRTRIM=2
export PS1='[\u@\h \w]\$ '

## Helper functions
dirname() {
  # Usage: dirname "path"
  printf '%s\n' "${1%/*}/"
}
basename() {
  # Usage: basename "path"
  : "${1%/}"
  printf '%s\n' "${_##*/}"
}

## Some handy aliases

# cd
alias ..="cd .."

# ls
alias ls='ls --color=auto'
alias ll='ls -l'
alias l1='ls -1'
alias la='ll -a'
alias lt='ll -t'
alias lh='ll -h'
alias lth='lt -h'

# git
if [ -f /usr/share/doc/git/contrib/completion/git-completion.bash ]; then
  source /usr/share/doc/git/contrib/completion/git-completion.bash
else
  if [ ! -f $HOME/git-completion.bash ]; then
    wget -q https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash \
      -O $HOME/git-completion.bash
  fi
  source $HOME/git-completion.bash
fi
alias g='git'
__git_complete g __git_main
alias gcommit='git commit'
__git_complete gcommit _git_commit
alias gco='git checkout'
__git_complete gco _git_checkout
alias gstatus='git status'
alias gdiff='git diff'
__git_complete gdiff _git_diff
alias gadd='git add'
__git_complete gadd _git_add
alias gpush='git push'
__git_complete gpush __git_push

# dnf
alias dnfs='dnf search'
alias dnfi='dnf install'

# feh
alias feh='feh --auto-zoom'
