# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# User specific environment and startup programs
export HISTIGNORE=$HISTIGNORE,fg

# Libreoffice crashes in wayland; TODO remove this
GDK_BACKEND=x11

export PATH="/var/lib/snapd/snap/bin"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# Setup Virtualenvwrapper
export VIRTUALENV_PYTHON=python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
if [ -x "$(command -v virtualenvwrapper.sh)" ]; then
  source virtualenvwrapper.sh
fi

# Python shell auto completion
export PYTHONSTARTUP=~/.pythonrc
