# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

export VISUAL=nvim
export EDITOR=nvim

export PROMPT_DIRTRIM=2
export PS1='[\u@\h \w]\$ '

## Helper functions
dirname() {
  # Usage: dirname "path"
  printf '%s\n' "${1%/*}/"
}
basename() {
  # Usage: basename "path"
  : "${1%/}"
  printf '%s\n' "${_##*/}"
}

## Some handy aliases

# when I think I'm in vim
alias :e=$EDITOR
alias :q='exit'
alias :w='echo not in vim'
alias :wq='echo not in vim'

# cd
alias ..="cd .."

# ls
alias ls='ls --color=auto'
alias ll='ls -l'
alias l1='ls -1'
alias la='ll -a'
alias lt='ll -t'
alias lh='ll -h'
alias lth='lt -h'

# tmux 256 color support
alias tmux="env TERM=xterm-256color tmux"

# set term variable over ssh
alias ssh="TERM=xterm ssh"

# git
if [ -f /usr/share/doc/git/contrib/completion/git-completion.bash ]; then
  source /usr/share/doc/git/contrib/completion/git-completion.bash
else
  if [ ! -f $HOME/git-completion.bash ]; then
    wget -q https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash \
      -O $HOME/git-completion.bash
  fi
  source $HOME/git-completion.bash
fi
alias g='git'
__git_complete g __git_main

# dnf
alias dnfs='dnf search'

# mpv
_mpv_use_media_globexpr=1
_mpv_media_globexpr='@(mkv)'
if [ ! -f $HOME/mpv-completion.bash ]; then
  wget -q https://raw.githubusercontent.com/2ion/mpv-bash-completion/master/gen.lua \
    -O /tmp/gen.lua
  chmod +x /tmp/gen.lua
  /tmp/gen.lua > $HOME/mpv-completion.bash
  rm /tmp/gen.lua
fi
source $HOME/mpv-completion.bash

# feh
alias feh='feh --auto-zoom'

# alacritty works better with xwayland
# alias alacritty='env WAYLAND_DISPLAY= alacritty'

alias heute-journal='mpv https://www.zdf.de/nachrichten/heute-journal'
